parameters:
  VstsFeedId: "f9245705-57f4-4044-ac91-85d34b6fe871"
  baseRepoId: ""
  baseBuildDefinitionId: ""
  coverageThreshold: 60
  coverageVariance: 5
  workingDirectory: $(System.DefaultWorkingDirectory)
  BuildServiceAccountId: "bf1ff99a-938b-4307-8b5d-344c8a51e178"
  moduleName: ""
  refBranch: "refs/heads/develop"
  pwsh: true

jobs:
  - job: Compile
    condition: succeeded()
    pool: Hosted VS2017

    steps:
      - task: gittools.gitversion.gitversion-task.GitVersion@3
        displayName: Build Version from GitVersion
      - powershell: |
          if(-not (gcm pwsh -ea SilentlyContinue)) {
                    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
                    iwr 'https://github.com/PowerShell/PowerShell/releases/download/v6.1.1/PowerShell-6.1.1-win-x64.msi' -OutFile $env:temp\pwsh.msi
                    Start-Process msiexec.exe -Wait -ArgumentList ('/I {0} /quiet' -f "$env:temp\pwsh.msi")
                    '##vso[task.prependpath]$env:ProgramFiles\PowerShell\6\'
                }

        displayName: "Install Core"
        enabled: true

      - task: PowerShell@2
        displayName: Compile Module
        inputs:
          targetType: "filePath"
          filePath: .build.ps1
          arguments: -Task CreateModuleManifest -ResolveDependency
          pwsh: true
          workingDirectory: ${{ parameters.workingDirectory }}
        env:
          SYSTEM_ACCESSTOKEN: $(system.accesstoken)
          BuildServiceAccountId: ${{ parameters.BuildServiceAccountId }}

      - task: PublishPipelineArtifact@0
        displayName: "Publish Module Artifact"
        inputs:
          targetPath: BuildOutput
        enabled: true
