parameters:
  baseRepoId: ""
  baseBuildDefinitionId: ""
  coverageThreshold: 60
  coverageVariance: 5
  workingDirectory: $(System.DefaultWorkingDirectory)
  moduleName: ""
  refBranch: "refs/heads/develop"
  pwsh: true

jobs:
- job: Compile
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: npm install
